INSERT INTO `charity-donation`.categories (id, name) VALUES (1, 'inne');
INSERT INTO `charity-donation`.categories (id, name) VALUES (2, 'ubrania, które nadają się do ponownego użycia');
INSERT INTO `charity-donation`.categories (id, name) VALUES (3, 'ubrania nie nadające się do ponownego użycia');
INSERT INTO `charity-donation`.categories (id, name) VALUES (4, 'atrybuty kuchenne');
INSERT INTO `charity-donation`.categories (id, name) VALUES (5, 'zabawki');
INSERT INTO `charity-donation`.categories (id, name) VALUES (6, 'książki');
INSERT INTO `charity-donation`.donations (id, city, phone_number, pick_up_comment, pick_up_date, pick_up_time, quantity, street, street_num, zip_code, institution_id) VALUES (1, 'Krosno', '505171299', '', '2019-08-23', '11:28:00', '2', 'Grzybowska', '93', '05-410', 2);
INSERT INTO `charity-donation`.donations (id, city, phone_number, pick_up_comment, pick_up_date, pick_up_time, quantity, street, street_num, zip_code, institution_id) VALUES (2, 'Warszawa', '505171299', '', '2019-09-14', '14:45:00', '1', 'Ziarnista, 4', '4', '05-410', 3);
INSERT INTO `charity-donation`.donations (id, city, phone_number, pick_up_comment, pick_up_date, pick_up_time, quantity, street, street_num, zip_code, institution_id) VALUES (3, 'Warszawa', '505171299', '', '2019-09-14', '14:45:00', '1', 'Ziarnista, 4', '4', '05-410', 3);
INSERT INTO `charity-donation`.donations (id, city, phone_number, pick_up_comment, pick_up_date, pick_up_time, quantity, street, street_num, zip_code, institution_id) VALUES (4, 'Warszawa', '505171299', '', '2019-09-14', '14:45:00', '1', 'Ziarnista, 4', '4', '05-410', 3);
INSERT INTO `charity-donation`.donations (id, city, phone_number, pick_up_comment, pick_up_date, pick_up_time, quantity, street, street_num, zip_code, institution_id) VALUES (5, 'Warszawa', '505171299', '', '2019-09-14', '14:45:00', '1', 'Ziarnista, 4', '4', '05-410', 3);
INSERT INTO `charity-donation`.donations (id, city, phone_number, pick_up_comment, pick_up_date, pick_up_time, quantity, street, street_num, zip_code, institution_id) VALUES (6, 'Warszawa', '505171299', '', '2019-09-14', '14:45:00', '1', 'Ziarnista, 4', '4', '05-410', 3);
INSERT INTO `charity-donation`.donations_categories (donation_id, categories_id) VALUES (1, 2);
INSERT INTO `charity-donation`.donations_categories (donation_id, categories_id) VALUES (2, 2);
INSERT INTO `charity-donation`.donations_categories (donation_id, categories_id) VALUES (3, 2);
INSERT INTO `charity-donation`.donations_categories (donation_id, categories_id) VALUES (4, 2);
INSERT INTO `charity-donation`.donations_categories (donation_id, categories_id) VALUES (5, 2);
INSERT INTO `charity-donation`.donations_categories (donation_id, categories_id) VALUES (6, 2);
INSERT INTO `charity-donation`.institutions (id, description, name) VALUES (1, 'Pomoc dzieciom z ubogich rodzin', 'Dbam o zdrowie');
INSERT INTO `charity-donation`.institutions (id, description, name) VALUES (2, 'Pomoc w wybudzaniu dzieci ze śpiączki', 'A kogo');
INSERT INTO `charity-donation`.institutions (id, description, name) VALUES (3, 'Pomoc osobom znajdującym się w trudnej sytuacji życiowej', 'Dla dzieci');
INSERT INTO `charity-donation`.institutions (id, description, name) VALUES (4, 'Pomoc dla osób nieposiadających miejsca zamieszkania', 'Bez domu');
INSERT INTO `charity-donation`.role (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO `charity-donation`.role (id, name) VALUES (2, 'ROLE_ADMIN');
INSERT INTO `charity-donation`.user (id, email, enabled, password, username) VALUES (1, 'email2@domena.pl', 1, '$2a$10$Gi7hMNitsvRfJn3sB314JunZMfEK3UL0b6S5k4BaH/SvZhoBe0KyG', 'user1');
INSERT INTO `charity-donation`.user (id, email, enabled, password, username) VALUES (4, 'a@a.pl', 1, '$2a$10$0VxABF6Fi9oWl9smk5KZhOd5QGUUn8iDI9/CPg4IafuzFp1PelLUm', 'aaa');
INSERT INTO `charity-donation`.user (id, email, enabled, password, username) VALUES (3, 'email@domena.pl', 1, '$2a$10$T9zeTXzXGVJOlNwTIDsDkus0mWBIqinHmNI5y99ztHLuSG1tXSAE.', 'angel1');
INSERT INTO `charity-donation`.user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO `charity-donation`.user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO `charity-donation`.user_role (user_id, role_id) VALUES (3, 2);
INSERT INTO `charity-donation`.user_role (user_id, role_id) VALUES (4, 1);